id: IF0B3B114
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T06:44:55.042029'
last_modified: '2022-05-31T06:44:55.042035'
parser: null
source_metadata:
  title: Paksam Wangpo Series
  language: bo
  description: 'Texts by and about Paksam Wangpo (dpag bsam dbang po, 1593–1641),
    the Fifth Drukchen:'
  volume:
    fCDD9:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      base_file: fCDD9.txt
      order: 1
      parent: Mahākāla
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
